#! /bin/bash

# make sure excute this script in hmm/

rm -r linear
rm -r bakis
rm -r nobakis

mkdir linear
echo "#######################"
echo "enter linear/"
cd linear
echo "#######################"

echo "training intial models"
../../DoKMeans -v; ../../DoInit -v; ../../DoTrain -v 0 19; ../../DoLabel -v 20;

cd ..
echo "#######################"
echo "enter bakis/"
echo "#######################"
mkdir bakis
cd bakis

echo "training bakis models"
cp ../../makeini.sh ./
cp ../linear/klaus.0.cl ./
./makeini.sh 20 
../../DoInit -v -t Bakis
../../DoTrain -v 0 19
../../DoXEvalChar -v 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
../../MkEvals
../../MkSummary>SUM

cd ..
echo "#######################"
echo "enter nobakis/"
echo "#######################"
mkdir nobakis
cd nobakis 

echo "training no-bakis models"
cp ../../makeini.sh ./
cp ../linear/klaus.0.cl ./
./makeini.sh 20
../../DoInit -v 
../../DoTrain -v 0 19
../../DoXEvalChar -v 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
../../MkEvals
../../MkSummary>SUM
