#! /bin/bash
		cat klaus.swu.def.word	\
		| sed "s/ü/ue/g"	\
	   	| sed "s/ä/ae/g"	\
	   	| sed "s/ö/oe/g"	\
		| sed "s/ß/ss/g"	\
		| sed "s/Ü/UE/g"	\
	   	| sed "s/Ä/AE/g" 	\
		| sed "s/Ö/OE/g"	\
		| sort	\
		| uniq  \
		>klaus.swu.def
