s/ - / @HYPHEN /g
s/ , / @COMMA /g
s/ ; / @SEMI-COLON /g
s/ : / @COLON /g
s/ ! / @EXCLAMATION-MARK /g
s/ ? / @QUESTION-MARK /g
s/ \. / @DOT /g
s/ \.\.\. / @DOTS /g
s/ ' / @QUOTE /g
s/ " / @DOUBLE-QUOTE /g
s/ ( / @LEFT-PAREN /g
s/ ) / @RIGHT-PAREN /g
s/ \* / @STAR /g
s/ \& / @AMPERSAND /g
s/ # / @CROSSED-OUT /g
s/ % / @PERCENT /g
s# / # @FORWARD-SLASH #g
s/ + / @PLUS /g
s/ < / @LESS-THAN /g
s/ > / @GREATER-THAN /g
s/ = / @EQUAL /g
