#! /bin/bash

# make sure excute this script in hmm/

echo "enter linear/"
cd linear

echo "trianing"
../../DoKMeans -v; ../../DoInit -v; ../../DoTrain -v 0 19; ../../DoLabel -v 20;
cp klaus.0.cl ../bakis

echo "enter bakis/"
cd ..
cd bakis

echo "trianing"
./makeini.sh 20; 
../../DoInit -v -t Bakis; 
../../DoTrain -v 0 19; 
